# Run IWYU
name: IWYU

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  checkout-and-check-formatting:
    runs-on: ubuntu-latest

    steps:
    - name: include what you use Github action
      uses: EmilGedda/include-what-you-use-action@v1.0
      with:
        compilation-database-path: '.'
        output-format: 'iwyu' # Or 'clang'
        no-error: 'false'
